networks:
  vaultwarden:
    external: false

services:
   vaultwarden:
     image: vaultwarden/server:1.32.3
     container_name: vaultwarden
     restart: always
     environment:
       SIGNUPS_ALLOWED: "true"
       SIGNUPS_VERIFY: false
       SIGNUPS_VERIFY_RESEND_TIME: 3600
       SIGNUPS_VERIFY_RESEND_LIMIT: 6
       # SIGNUPS_DOMAINS_WHITELIST: example.com,example.net,example.org
       ORG_EVENTS_ENABLED: false
       # ORG_CREATION_USERS: 
       # INVITATIONS_ALLOWED: true
       # INVITATION_ORG_NAME: Vaultwarden
       # INVITATION_EXPIRATION_HOURS: 120
       DATA_FOLDER: "data"
       RSA_KEY_FILENAME: data/rsa_key
       ICON_CACHE_FOLDER: data/icon_cache
       ATTACHMENTS_FOLDER: data/attachments
       SENDS_FOLDER: data/sends
       TMP_FOLDER: data/tmp
       TEMPLATES_FOLDER: data/templates
       RELOAD_TEMPLATES: false
       WEB_VAULT_FOLDER: web-vault/
       WEB_VAULT_ENABLED: true
       DATABASE_URL: data/db.sqlite3
       #ENABLE_DB_WAL: true
       DB_CONNECTION_RETRIES: 15
       DATABASE_TIMEOUT: 30
       DATABASE_MAX_CONNS: 10
       #DATABASE_CONN_INIT: ""
       ENABLE_WEBSOCKET: true
       # PUSH_ENABLED: false
       # PUSH_INSTALLATION_ID: CHANGEME
       # PUSH_INSTALLATION_KEY: CHANGEME
       # PUSH_RELAY_URI: https://push.bitwarden.com
       # PUSH_IDENTITY_URI: https://identity.bitwarden.com
       JOB_POLL_INTERVAL_MS: 30000
       SEND_PURGE_SCHEDULE: "0 5 * * * *"
       TRASH_PURGE_SCHEDULE: "0 5 0 * * *"
       INCOMPLETE_2FA_SCHEDULE: "30 * * * * *"
       EMERGENCY_NOTIFICATION_REMINDER_SCHEDULE: "0 3 * * * *"
       EMERGENCY_REQUEST_TIMEOUT_SCHEDULE: "0 7 * * * *"
       EVENT_CLEANUP_SCHEDULE: "0 10 0 * * *"
       EVENTS_DAYS_RETAIN: 7
       AUTH_REQUEST_PURGE_SCHEDULE: "30 * * * * *"
       DUO_CONTEXT_PURGE_SCHEDULE: "30 * * * * *"
       DOMAIN: http://localhost
       SENDS_ALLOWED: true
       # HIBP_API_KEY:  #HaveIBeenPwned API Key, request it here: https://haveibeenpwned.com/API/Key
       # ORG_ATTACHMENT_LIMIT: 
       # USER_ATTACHMENT_LIMIT: 
       # USER_SEND_LIMIT: 
       TRASH_AUTO_DELETE_DAYS: 30
       INCOMPLETE_2FA_TIME_LIMIT: 3
       DISABLE_ICON_DOWNLOAD: false
       # EMERGENCY_ACCESS_ALLOWED: true
       # EMAIL_CHANGE_ALLOWED: true
       PASSWORD_ITERATIONS: 600000
       PASSWORD_HINTS_ALLOWED: true
       SHOW_PASSWORD_HINT: true
       IP_HEADER: X-Real-IP
       ICON_SERVICE: internal
       ICON_REDIRECT_CODE: 302
       ICON_CACHE_TTL: 2592000
       ICON_CACHE_NEGTTL: 259200
       ICON_DOWNLOAD_TIMEOUT: 10
       HTTP_REQUEST_BLOCK_REGEX: '^(192\.168\.0\.[0-9]+|192\.168\.1\.[0-9]+)$'
       HTTP_REQUEST_BLOCK_NON_GLOBAL_IPS: true
       # EXPERIMENTAL_CLIENT_FEATURE_FLAGS: fido2-vault-credentials
       # REQUIRE_DEVICE_EMAIL: false
       # EXTENDED_LOGGING: true
       # LOG_TIMESTAMP_FORMAT: "%Y-%m-%d %H:%M:%S.%3f"
       # USE_SYSLOG: false
       # LOG_FILE: /path/to/log
       LOG_LEVEL: info
       # ADMIN_TOKEN: Vy2VyYTTsKPv8W5aEOWUbB/Bt3DEKePbHmI4m9VcemUMS2rEviDowNAFqYi1xjmp
       # DISABLE_ADMIN_TOKEN: false
       ADMIN_RATELIMIT_SECONDS: 300
       ADMIN_RATELIMIT_MAX_BURST: 3
       ADMIN_SESSION_LIFETIME: 20
       # ALLOWED_IFRAME_ANCESTORS: 
       LOGIN_RATELIMIT_SECONDS: 60
       LOGIN_RATELIMIT_MAX_BURST: 10
       # INCREASE_NOTE_SIZE_LIMIT: false
       # ENFORCE_SINGLE_ORG_WITH_RESET_PW_POLICY: false
       # YUBICO_CLIENT_ID: 11111
       # YUBICO_SECRET_KEY: AAAAAAAAAAAAAAAAAAAAAAAA
       # YUBICO_SERVER: http://yourdomain.com/wsapi/2.0/verify
       # DUO_IKEY: <Client ID>
       # DUO_SKEY: <Client Secret>
       # DUO_HOST: <API Hostname>
       # DUO_USE_IFRAME: false
       EMAIL_TOKEN_SIZE: 6
       EMAIL_EXPIRATION_TIME: 600
       EMAIL_ATTEMPTS_LIMIT: 3
       # EMAIL_2FA_ENFORCE_ON_VERIFIED_INVITE: false
       # EMAIL_2FA_AUTO_FALLBACK: false
       # DISABLE_2FA_REMEMBER: false
       # AUTHENTICATOR_DISABLE_TIME_DRIFT: false
       # SMTP_HOST: smtp.domain.tld
       # SMTP_FROM: vaultwarden@domain.tld
       # SMTP_FROM_NAME: Vaultwarden
       # SMTP_USERNAME: username
       # SMTP_PASSWORD: password
       # SMTP_TIMEOUT: 15
       # SMTP_SECURITY: starttls
       # SMTP_PORT: 587
       # USE_SENDMAIL: false
       # SENDMAIL_COMMAND: "/path/to/sendmail"
       # SMTP_AUTH_MECHANISM: 
       # HELO_NAME: 
       # SMTP_EMBED_IMAGES: true
       # SMTP_DEBUG: false
       # SMTP_ACCEPT_INVALID_CERTS: false
       # SMTP_ACCEPT_INVALID_HOSTNAMES: false
       # ROCKET_ADDRESS: 0.0.0.0
       # ROCKET_PORT: 8000
       # ROCKET_TLS: {certs: "/path/to/certs.pem",key: "/path/to/key.pem"}
     volumes:
       - ./vw-data:/data
     ports:
       - 11001:80
