networks:
  gitea:
    external: false

secrets:
  mysql_root_pw:
    file: ./secrets/mysql_root_pw
  mysql_db_pw:
    file: ./secrets/mysql_db_pw

services:
  server:
    image: gitea/gitea:1.21.11
    container_name: gitea
    secrets:
      - mysql_db_pw
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    secrets:
      - mysql_root_pw
      - mysql_db_pw
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_pw
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_db_pw
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql
