volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.6
    container_name: nextcloud-mysql
    restart: always
    secrets:
      - mysql_db_pw
      - mysql_root_pw
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_pw
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_db_pw
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    container_name: nextcloud
    restart: always
    secrets:
      - mysql_db_pw
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_db_pw
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

secrets:
  mysql_root_pw:
    file: /docker/secrets/mysql_root_pw.txt
  mysql_db_pw:
    file: /docker/secrets/mysql_db_pw.txt
